CUDNN:
  BENCHMARK: true
  DETERMINISTIC: false
  ENABLED: true
DATA_DIR: 'data' 
DATASET: 'mydata'
GPUS: '0'
OUTPUT_DIR: 'output_mydata' 
MODEL: 'VoxelFusionNet' 
LOG_DIR: 'log'
WORKERS: 8
PRINT_FREQ: 500
NUM_JOINTS: 17
SEED: 1

NETWORK:
  IMAGE_SIZE: 
    - 1920
    - 1080
  HEATMAP_SIZE:
    - 480
    - 270
  MID_FDIM: 32 # 16
  HEAD_DIM: 32
  SIGMA: 2.0

PICT_STRUCT:
  GRID_SIZE:
    - 2.0
    - 2.0
    - 2.0
  CUBE_SIZE:
    - 64
    - 64
    - 64

DDP:
  NUM_PROCESS_PER_NODE: 1
  PORT: '10100'
